
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: prometheus
  ports:
  - port: 80
    targetPort: 9090
    name: prometheus-web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "prometheus-basicauth"
    # https://docs.traefik.io/user-guide/kubernetes/#basic-authentication
    external-dns.alpha.kubernetes.io/target: traefik-gke.jasongwartz.com # This should be the DNS entry of the traefik ingress controller
    # https://github.com/kubernetes-incubator/external-dns/blob/master/docs/faq.md#user-content-are-other-ingress-controllers-supported
spec:
  rules:
  - host: "prometheus.jasongwartz.com"
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 80
