kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik
  namespace: ingress-controller
data:
  traefik.toml: |
    
    defaultEntryPoints = ["http","https"]
    
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
    #    regex = "^http://jasongwartz.com"
    #    regex = "^http://(jasongwartz.com|gwartz.me|twoidiots.eu)/(.*)"
    #    replacement = "https://www.$1/$2"
        entrypoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    
    [kubernetes]

    [web]
    readOnly = true
      [web.metrics.prometheus]


    [acme]
    email = "jason.gwartz@gmail.com"
    storage = "/nfs/traefik/acme.json"
    entryPoint = "https"
    OnHostRule = true
    
    # [metrics]
    #   # To enable Traefik to export internal metrics to Prometheus
    #   [metrics.prometheus]
    #   # Name of the related entry point
    #   #
    #   # Optional
    #   # Default: "traefik"
    #   #
    #   entryPoint = "traefik"