kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik
  namespace: ingress-controller
data:
  traefik.toml: |
    
    defaultEntryPoints = ["http","https"]
    
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        regex = "^http://jasongwartz.com/(.*)"
        #regex = "^http://(jasongwartz.com|gwartz.me|twoidiots.eu)/(.*)"
        replacement = "https://www.jasongwartz.com/$1"
        entrypoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    
    [kubernetes]

    [web]
    readOnly = true
      [web.metrics.prometheus]


    [acme]
    dnsProvider = "cloudflare"
    email = "jason.gwartz@gmail.com"
    storage = "/nfs/traefik/acme.json"
    entryPoint = "https"
    OnHostRule = true
    acmeLogging= true
