---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: ingress-controller
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.5-alpine
        name: traefik-ingress-lb
        env:
        - name: CLOUDFLARE_EMAIL
          valueFrom:
            secretKeyRef:
              name: traefik-cloudflare
              key: email
        - name: CLOUDFLARE_API_KEY
          valueFrom:
            secretKeyRef:
              name: traefik-cloudflare
              key: api_key
        volumeMounts:
        # name must match the volume name below
        - name: traefik-gke
          mountPath: "/traefik"
        - name: traefik-config
          mountPath: /etc/traefik
      volumes:
      - name: traefik-gke
        persistentVolumeClaim:
          claimName: traefik-gke
      - name: traefik-config
        configMap:
          name: traefik
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: ingress-controller
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik-gke.jasongwartz.com
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: ingress-controller
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: ingress-controller
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: traefik.gwartz.me
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: 80
