---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:alpine
        name: traefik-ingress-lb
        volumeMounts:
        # name must match the volume name below
        - name: traefik-nfs
          mountPath: "/nfs/traefik"
        - name: traefik-config
          mountPath: /etc/traefik
      volumes:
      - name: traefik-nfs
        persistentVolumeClaim:
          claimName: traefik-nfs
      - name: traefik-config
        configMap:
          name: traefik
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: ingress-controller
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
  # type: NodePort
  externalIPs:
  - "10.0.2.30"

