apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-nfs
  namespace: ingress-controller
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.1.5
    path: "/volume1/kubernetes-nfs/traefik"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-nfs
  namespace: ingress-controller
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
